spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=jwtcrud;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Kiolopo09
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.port=8080